const buildingData = [
  {
    name: "Engineering Science Building (DIET)",
    year: 1998,
    type: "Concrete Frame",
    storeys: 3,
    occupancy: "Academic and Office",
  },
  {
    name: "Biological Sciences Building",
    year: 1997,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Physical Science Building",
    year: 1992,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Interdisciplinary Research Building",
    year: 2016,
    type: "Concrete Frame",
    storeys: 7,
    occupancy: "Specialized Facilities",
  },
  {
    name: "International House 1",
    year: 2008,
    type: "Concrete Frame",
    storeys: 4,
    occupancy: "Mixed-Use Buildings",
  },
  {
    name: "College of Information and Technology (CEIT)",
    year: 2006,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "University Library",
    year: 2004,
    type: "Concrete Frame",
    storeys: 6,
    occupancy: "Academic and Office",
  },
  {
    name: "Agricultural Science Building (CAFENR)",
    year: 2008,
    type: "Concrete Frame",
    storeys: 3,
    occupancy: "Academic and Office",
  },
  {
    name: "Crop Science Building",
    year: 1994,
    type: "Concrete Frame",
    storeys: 3,
    occupancy: "Academic and Office",
  },
  {
    name: "Animal Science Building",
    year: 1994,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Veterinary Medicine Classroom (CVMBS)",
    year: 2004,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Veterinary Hospital",
    year: 2003,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Specialized Facilities",
  },
  {
    name: "Old CEMDS Building",
    year: 1986,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Human Kinetics Building (Gymnasium)",
    year: 2006,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Specialized Facilities",
  },
  {
    name: "College of Education",
    year: 1993,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Research Center Building",
    year: 1986,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Specialized Facilities",
  },
  {
    name: "International House 2",
    year: 2009,
    type: "Concrete Frame",
    storeys: 4,
    occupancy: "Mixed-Use Buildings",
  },
  {
    name: "OSAS Building",
    year: 2006,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Mixed-Use Buildings",
  },
  {
    name: "ITC Building",
    year: 2003,
    type: "Concrete Frame",
    storeys: 5,
    occupancy: "Academic and Office",
  },
  {
    name: "Languages & Humanities Building (CAS)",
    year: 2002,
    type: "Concrete Frame",
    storeys: 3,
    occupancy: "Academic and Office",
  },
  {
    name: "College of Criminal Justice (CCJ)",
    year: 2018,
    type: "Concrete Frame",
    storeys: 4,
    occupancy: "Academic and Office",
  },
  {
    name: "CEMDS Building",
    year: 2016,
    type: "Concrete Frame",
    storeys: 5,
    occupancy: "Academic and Office",
  },
  {
    name: "Graduate School & Open Learning College",
    year: 2020,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Bahay ng Alumni",
    year: 2023,
    type: "Concrete Frame",
    storeys: 2,
    occupancy: "Academic and Office",
  },
  {
    name: "Engineering Building",
    year: 2007,
    type: "Concrete Frame",
    storeys: 4,
    occupancy: "Academic and Office",
  },
];
